[package]
name = "nuit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nuit-derive = { path = "derive" }
nuit-shared = { path = "shared" }

[target.'cfg(target_os = "macos")'.dependencies]
nuit-swiftui-bridge = { path = "bridge/swiftui" }

[workspace]
members = [
    "bridge/swiftui",
    "derive",
    "shared",
]

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
