[package]
name = "nuit-core"
description = "Core structures and traits for Nuit"
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
ref-cast = "1.0"
