[package]
name = "nuit-core"
version = "0.0.2"
edition = "2021"
description = "Core structures and traits for Nuit"
homepage = "https://github.com/fwcd/nuit"
license = "GPL-3.0-or-later"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
