import NuitBridgeSwiftUICore

enum ModifierNode: Codable, Hashable {
    case padding(insets: Insets)
    case position(position: Vec2<Double>)
    case offset(delta: Vec2<Double>)
    case opacity(opacity: Double)
    case frame(frame: Frame, alignment: Alignment)
    case fill(style: Style)
    case font(font: Font)
    case foregroundStyle(style: Style)
    case background(style: Style, safeAreaIgnoringEdges: EdgeSet)
    case scaleEffect(factor: Double, anchor: UnitPoint)
    case rotationEffect(angle: Angle, anchor: UnitPoint)
    case help(text: String)
    case navigationTitle(title: String)
    case navigationSubtitle(subtitle: String)
    case navigationTitleDisplayMode(displayMode: NavigationTitleDisplayMode)
    case border(style: Style, width: Double)
    case shadow(color: Style, radius: Double, offset: Vec2<Double>)
    case blur(radius: Double)
    case cornerRadius(radius: Double)
    case overlay(style: Style, alignment: Alignment)
    case zIndex(zIndex: Double)
    case hidden(isHidden: Bool)
    case disabled(isDisabled: Bool)
    case grayscale(intensity: Double)
    case brightness(amount: Double)
    case contrast(amount: Double)
    case saturation(amount: Double)
    case hueRotation(angle: Angle)
    case clipped
}
