[package]
name = "nuit-bridge-swiftui"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
path = "rust/lib.rs"

[dependencies]
nuit-core = { path = "../nuit-core" }
