#!/bin/bash

set -e
cd "$(dirname $0)/.."

# TODO: Figure out if we can configure this properly from Cargo.toml
# [lints.clippy] seems to be unstable currently.

cargo clippy --all-targets --all-features -- -W clippy::pedantic
