name: Publish

on:
  push:
    tags:
    - '*'
  workflow_dispatch:

# Fail CI on warnings
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - name: Install system dependencies
        run: sudo apt-get install -y libadwaita-1-dev libgtk-4-dev
      - name: Test package
        run: cargo test --all --all-features
      - name: Lint package
        run: cargo clippy --all-targets --all-features -- -W clippy::pedantic
      - name: Publish nuit-derive
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
        working-directory: nuit-derive
      - name: Publish nuit-core
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
        working-directory: nuit-core
      - name: Publish nuit-bridge-adwaita
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
        working-directory: nuit-bridge-adwaita
      - name: Publish nuit-bridge-swiftui
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
        working-directory: nuit-bridge-swiftui
      - name: Publish nuit
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
