[package]
name = "nuit-derive"
version = "0.0.5"
edition = "2021"
description = "Derive macros for Nuit"
homepage = "https://github.com/fwcd/nuit"
license = "GPL-3.0-or-later"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
