[package]
name = "nuit-derive"
description = "Derive macros for Nuit"
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
